### ISSUE TITLE
Peer-peer code review

### ISSUE THREAD

**Issue by Kayonga99** [Kayonga99/My-Portfolio#18]
## Hey @Kayonga99  your code will look cleaner if you remove the commented code in the index.html file, you are supposed to take it out not commenting it. Kindly remove it to make your code cleaner.

https://github.com/Kayonga99/My-Portfolio/blob/88c77da2d1f9590f661a29c0c8f5403109284277/index.html#L68

**Comment by BouaikIlham** [comment]
Good job so far, for me nothing else to say.
